### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by mrjacobbloom** [mrjacobbloom/mrjacobbloom.github.io#1]
- [x] Update notochord gif to showoff notochord-gui notochord.herokuapp.com
- [x] Update projects page to be more interactive/have a writeup on each thing
- [x] Add Lumpy (and Echo?) to projects page
- [x] Just add Echo. Just do it. Also, Playback is in TS now
- [x] Update music page
- [x] New graphic behind "So yeah, I can code if you want"
- [x] ~~Invert colors on sheet music gif? I don't have After Effects anymore so that might be super hard...~~
- [x] Basic SEO stuff (description meta tags and stuff)
- [x] Look into switching Hero from JS fitting to css object-fit if well-supported enough
- [x] ~~Add some kind of technical skills list to code page to bring it to content parity with my resume~~
  - note: resume also contains education history
- [x] Carousel play videos on change slide?
